#!bin/bash
IMAGE=$(pwd)/out/arch/arm64/boot/Image.gz-dtb
git clone -j32 https://github.com/najahiiii/aarch64-linux-gnu -b 4.9-mirror gcc
git clone -j32 https://github.com/ryan-andri/aarch64-linaro-linux-gnu-4.9 -b master linaro
git clone -j32 https://github.com/najahiiii/priv-toolchains -b elf/gcc-10.0.0/arm64 gccc
echo "clone any kornol plox"
git clone https://github.com/fadlyas/anykernel2 
echo "Clone any kornol plox"
git clone https://github.com/fadlyas/anykernel2 gnu
echo "Clone any kornol plox"
git clone https://github.com/fadlyas/anykernel2 cclang
echo "Time To Compile All"
echo "GCC 4.9 coming"
GCC="$(pwd)/gcc/bin/aarch64-linux-android-"
echo "Linaro GCC 4.9 coming"
LINARO="$(pwd)/linaro/bin/aarch64-linux-gnu-"
echo "GCC 10 ELF Coming"
ELF="$(pwd)/gccc/bin/aarch64-elf-"
echo "Time To Compile All"
curl -s -F chat_id=-1001158707255 -F sticker="CAADBQADsAADfULDLi7M_9kl2KMnFgQ" https://api.telegram.org/bot804021619:AAGsNtz-PiDmnuyoIg_lpKVghK_8WmxSbIQ/sendSticker
curl -s -X POST https://api.telegram.org/bot804021619:AAGsNtz-PiDmnuyoIg_lpKVghK_8WmxSbIQ/sendMessage?chat_id=-1001158707255 -d "disable_web_page_preview=true" -d "parse_mode=html&text=<b>SteelHeart Darkside version is up!!</b>%0ACompile Started"'!'"%0A<b>For device</b> <code>Rolex (Redmi 4A)</code>%0A<b>For Android Oreo or Android Pie</b>%0A<b>Under Commit</b> <code>$(git log --pretty=format:'"%h : %s"' -1)</code>%0A<b>Compiler</b> <code>$(${GCC}gcc --version | head -n 1)</code>%0AStarted on <code>$(TZ=Asia/Jakarta date)</code>%0A<b>Build Status:</b> #untested"
tanggal=$(TZ=Jakarta date +'%H%M-%d%m%y')
START=$(date +"%s")
export ARCH=arm64
export KBUILD_BUILD_USER=mhmmdfas
export KBUILD_BUILD_HOST=steelheart
export USE_CCACHE=1
export CACHE_DIR=~/.ccache
# Fin Error
function finerr() {
    curl -s -X POST "https://api.telegram.org/bot804021619:AAGsNtz-PiDmnuyoIg_lpKVghK_8WmxSbIQ/sendMessage" \
        -d chat_id="-1001158707255" \
        -d "disable_web_page_preview=true" \
        -d "parse_mode=markdown" \
        -d text="SteelHeart Build throw an error(s)"
    exit 1
}
make -s -C $(pwd) -j48 O=out rolex_defconfig
make -s -C $(pwd) CROSS_COMPILE="${GCC}" O=out -j60 -l50 2>&1| tee build.log
if ! [ -a $IMAGE ]; then
	exit 1
fi
cp out/arch/arm64/boot/Image.gz-dtb anykernel2/zImage
paste
cd anykernel2
zip -r9 SteelHeart-Hardcore-${tanggal}.zip *
END=$(date +"%s")
DIFF=$(($END - $START))
curl -F chat_id="-1001158707255" -F document=@"SteelHeart-Hardcore-${tanggal}.zip " -F "disable_web_page_preview=true" -F "parse_mode=html" -F caption="Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) second(s) | #sunny | #stable | <b>$(${GCC}gcc --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g')</b>" https://api.telegram.org/bot804021619:AAGsNtz-PiDmnuyoIg_lpKVghK_8WmxSbIQ/sendDocument
cd ..
rm -rf out
rm -rf anykernel2

make -s -C $(pwd) -j48 O=out rolex_defconfig
make -s -C $(pwd) CROSS_COMPILE="${LINARO}" O=out -j60 -l50 2>&1| tee build.log
if ! [ -a $IMAGE ]; then
	exit 1
fi
cp out/arch/arm64/boot/Image.gz-dtb gnu/zImage
paste
cd gnu
zip -r9 SteelHeart-Hardcore-${tanggal}.zip *
END=$(date +"%s")
DIFF=$(($END - $START))
curl -F chat_id="-1001158707255" -F document=@"SteelHeart-Hardcore-${tanggal}.zip " -F "disable_web_page_preview=true" -F "parse_mode=html" -F caption="Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) second(s) | #sunny | #stable | <b>$(${LINARO}gcc --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g')</b>" https://api.telegram.org/bot804021619:AAGsNtz-PiDmnuyoIg_lpKVghK_8WmxSbIQ/sendDocument
cd ..
rm -rf out
rm -rf gnu

make -s -C $(pwd) -j48 O=out rolex_defconfig
make -s -C $(pwd) CROSS_COMPILE="${ELF}" O=out -j60 -l50 2>&1| tee build.log
if ! [ -a $IMAGE ]; then
	exit 1
fi
cp out/arch/arm64/boot/Image.gz-dtb cclang/zImage
paste
cd cclang
zip -r9 SteelHeart-Hardcore-${tanggal}.zip *
END=$(date +"%s")
DIFF=$(($END - $START))
curl -F chat_id="-1001158707255" -F document=@"SteelHeart-Hardcore-${tanggal}.zip " -F "disable_web_page_preview=true" -F "parse_mode=html" -F caption="Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) second(s) | #sunny | #stable | <b>$(${ELF}gcc --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g')</b>" https://api.telegram.org/bot804021619:AAGsNtz-PiDmnuyoIg_lpKVghK_8WmxSbIQ/sendDocument
cd ..
rm -rf out
rm -rf cclang
